### ISSUE TITLE
严重问题

### ISSUE THREAD

**Issue by lyzqw** [jarvisyin/SquareVideoRecorder#7]
此项目移动明显, 屏幕掉帧, 花屏!

**Comment by t14z** [comment]
移动明显是什么意思发自我的iPhone------------------ 原始邮件 ------------------发件人: 坚持编程  <notifications@github.com>发送时间: 2019年1月16日 07:47收件人: jarvisyin/SquareVideoRecorder <SquareVideoRecorder@noreply.github.com>抄送: Subscribed <subscribed@noreply.github.com>主题: 回复：[jarvisyin/SquareVideoRecorder] 严重问题 (#7)此项目移动明显, 屏幕掉帧, 花屏!

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jarvisyin/SquareVideoRecorder","title":"jarvisyin/SquareVideoRecorder","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jarvisyin/SquareVideoRecorder"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"严重问题 (#7)"}],"action":{"name":"View Issue","url":"https://github.com/jarvisyin/SquareVideoRecorder/issues/7"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jarvisyin/SquareVideoRecorder/issues/7",
"url": "https://github.com/jarvisyin/SquareVideoRecorder/issues/7",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lyzqw** [comment]
自己看错了, 还好吧, 拍摄质量

**Comment by t14z** [comment]
你是在说反话吗？发自我的iPhone------------------ 原始邮件 ------------------发件人: 坚持编程  <notifications@github.com>发送时间: 2019年1月30日 14:42收件人: jarvisyin/SquareVideoRecorder <SquareVideoRecorder@noreply.github.com>抄送: Mr. <jarvis.yin@gmail.com>, Comment <comment@noreply.github.com>主题: 回复：[jarvisyin/SquareVideoRecorder] 严重问题 (#7)自己看错了, 还好吧, 拍摄质量

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jarvisyin/SquareVideoRecorder","title":"jarvisyin/SquareVideoRecorder","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/jarvisyin/SquareVideoRecorder"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Git-lyz in #7: 自己看错了, 还好吧, 拍摄质量"}],"action":{"name":"View Issue","url":"https://github.com/jarvisyin/SquareVideoRecorder/issues/7#issuecomment-458830710"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/jarvisyin/SquareVideoRecorder/issues/7#issuecomment-458830710",
"url": "https://github.com/jarvisyin/SquareVideoRecorder/issues/7#issuecomment-458830710",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
